redirects:
  about/five-minute-quickstart: /getting-started/five-minute-quickstart.md
  faq/how-do-I-avoid-duplicates-in-imports: /faq/how-do-I-avoid-duplicating-data.md
  faq/how-do-i-add-images-to-my-elements: /guides/images.md
  faq/how-do-i-change-element-shape: /guides/shapes.md
  faq/how-do-i-change-element-shapes-from-circles-to-squares: /faq/how-do-i-change-element-shape.md
  faq/how-do-i-decorate-a-single-element-or-connection: /guides/direct-decorations.md
  faq/how-do-i-delete-a-project: /faq/how-do-i-delete-a-project-map-or-view.md
  faq/how-to-add-background-image: /guides/images.md
  faq/how-to-add-contributors: /overview/collaboration.md#add-a-contributor
  faq/how-to-scale-elements-no-text-size-change: /faq/how-do-i-control-label-size-while-scaling-element-size.md
  faq/my-pdf-wont-export: faq/my-PDF-wont-export.md
  faq/who-is-allowed-to-edit-my-project: /overview/actions-and-permissions.md
  getting-started/adding-a-collaborator: /getting-started/overview.md#adding-a-collaborator-permalink
  getting-started/basic-vs-advanced-editor: /overview/view-editors.md
  getting-started/building-your-first-map: /getting-started/overview.md#building-your-first-map-permalink
  getting-started/decorations: /getting-started/overview.md#decorations-permalink
  getting-started/five-minute-quickstart: /#five-minute-quickstart
  getting-started/hiding-elements-connections: /getting-started/overview.md#hiding-elements-connections-permalink
  getting-started/introduction: /getting-started/first-steps.md
  getting-started/overview: /getting-started/first-steps.md
  getting-started/picking-a-template: /getting-started/overview.md#picking-a-template-permalink
  getting-started/projects-vs-maps-vs-views.md: /overview/data-architecture.md
  guides/advanced-settings: /guides/settings-reference.md
  guides/attributes: /guides/fields.md
  guides/basics/fields: /guides/fields.md
  guides/collaboration: /overview/collaboration.md
  guides/controls/field-filter-control: /guides/controls/filter-control.md
  guides/controls/field-showcase-control: /guides/controls/showcase-control.md
  guides/controls/showcase-toggle-control: /guides/controls/showcase-control.md
  guides/data-editor: /guides/table.md
  guides/default-settings: /guides/default-view-settings.md
  guides/embeds: /guides/share-and-embed.md
  guides/index: /guides/guides.md
  guides/layout: /guides/layouts.md
  guides/organizations: /guides/pro-workspaces.md
  guides/perspectives-advanced: /overview/user-interfaces/view-editors.md#advanced-editor
  guides/perspectives: /guides/views.md
  guides/project-architecture: /overview/kumus-architecture.md
  guides/sharing: /guides/embeds.md
  guides/snap-to: /guides/layouts/snap-to.md
  guides/views-advanced: /overview/view-editors.md#advanced-editor
  guides/wizard: /guides/quick-actions.md
  introduction: /overview/the-essentials.md
  overview/accounts-and-plans: /overview/accounts-and-workspaces.md
  overview/basic-vs-advanced-editor: /overview/view-editors.md
  overview/data-architecture: /overview/kumus-architecture.md
  overview/personal-and-organization-accounts: /overview/accounts-and-plans.md
  overview/the-essentials: /getting-started/first-steps.md

  # Previous versions of Gitbook used .html file extensions for pages.
  # These redirects were generated when we migrated to Gitbook.com and
  # shouldn't need to be touched again.
  about/how-does-it-work.html: about/how-does-it-work.md
  about/what-is-kumu.html: about/what-is-kumu.md
  about/where-can-i-get-help.html: about/where-can-i-get-help.md
  enterprise/backing-up-enterprise-data.html: enterprise/backing-up-enterprise-data.md
  enterprise/changelog.html: enterprise/changelog.md
  enterprise/command-line-utilities.html: enterprise/command-line-utilities.md
  enterprise/configuration.html: enterprise/configuration.md
  enterprise/creating-user-accounts.html: enterprise/creating-user-accounts.md
  enterprise/getting-started-with-virtualbox.html: enterprise/getting-started-with-virtualbox.md
  enterprise/getting-started-with-vmware.html: enterprise/getting-started-with-vmware.md
  enterprise/index.html: enterprise/index.md
  enterprise/restoring-enterprise-data.html: enterprise/restoring-enterprise-data.md
  enterprise/single-sign-on.html: enterprise/single-sign-on.md
  enterprise/ssh-access.html: enterprise/ssh-access.md
  enterprise/upgrading.html: enterprise/upgrading.md
  faq/can-I-change-the-font.html: faq/can-I-change-the-font.md
  faq/embed-doesnt-work-what-do-i-do.html: faq/embed-doesnt-work-what-do-i-do.md
  faq/how-can-i-remove-unwanted-legend-entries.html: faq/how-can-i-remove-unwanted-legend-entries.md
  faq/how-can-readers-switch-maps-and-views.html: faq/how-can-readers-switch-maps-and-views.md
  faq/how-do-I-add-arrows-to-my-connections.html: faq/how-do-I-add-arrows-to-my-connections.md
  faq/how-do-I-avoid-duplicating-data.html: faq/how-do-I-avoid-duplicating-data.md
  faq/how-do-I-hide-labels.html: faq/how-do-I-hide-labels.md
  faq/how-do-i-add-annotations.html: faq/how-do-i-add-annotations.md
  faq/how-do-i-add-documents-to-profiles.html: faq/how-do-i-add-documents-to-profiles.md
  faq/how-do-i-add-more-than-one-element-with-the-same-label.html: faq/how-do-i-add-more-than-one-element-with-the-same-label.md
  faq/how-do-i-add-text-to-connections.html: faq/how-do-i-add-text-to-connections.md
  faq/how-do-i-adjust-arrow-size.html: faq/how-do-i-adjust-arrow-size.md
  faq/how-do-i-change-connection-curvature.html: faq/how-do-i-change-connection-curvature.md
  faq/how-do-i-change-element-text-position.html: faq/how-do-i-change-element-text-position.md
  faq/how-do-i-change-font-color.html: faq/how-do-i-change-font-color.md
  faq/how-do-i-change-font-size.html: faq/how-do-i-change-font-size.md
  faq/how-do-i-change-the-order-of-control-options.html: faq/how-do-i-change-the-order-of-control-options.md
  faq/how-do-i-cite-kumu.html: faq/how-do-i-cite-kumu.md
  faq/how-do-i-collapse-duplicate-connections.html: faq/how-do-i-collapse-duplicate-connections.md
  faq/how-do-i-control-label-size-while-scaling-element-size.html: faq/how-do-i-control-label-size-while-scaling-element-size.md
  faq/how-do-i-control-text-wrapping.html: faq/how-do-i-control-text-wrapping.md
  faq/how-do-i-convert-a-project-from-private-to-public.html: faq/how-do-i-convert-a-project-from-private-to-public.md
  faq/how-do-i-convert-a-project-from-public-to-private.html: faq/how-do-i-convert-a-project-from-public-to-private.md
  faq/how-do-i-copy-a-map-to-another-project.html: faq/how-do-i-copy-a-map-to-another-project.md
  faq/how-do-i-create-ghost-elements.html: faq/how-do-i-create-ghost-elements.md
  faq/how-do-i-customize-link-text-in-popovers.html: faq/how-do-i-customize-link-text-in-popovers.md
  faq/how-do-i-customize-the-order-of-my-legend.html: faq/how-do-i-customize-the-order-of-my-legend.md
  faq/how-do-i-delete-a-project-map-or-view.html: faq/how-do-i-delete-a-project-map-or-view.md
  faq/how-do-i-delete-data-from-my-project.html: faq/how-do-i-delete-data-from-my-project.md
  faq/how-do-i-downgrade-my-subscription.html: faq/how-do-i-downgrade-my-subscription.md
  faq/how-do-i-edit-virtual-elements.html: faq/how-do-i-edit-virtual-elements.md
  faq/how-do-i-get-rid-of-unneeded-controls.html: faq/how-do-i-get-rid-of-unneeded-controls.md
  faq/how-do-i-hide-elements-without-connections.html: faq/how-do-i-hide-elements-without-connections.md
  faq/how-do-i-hide-images-from-the-map.html: faq/how-do-i-hide-images-from-the-map.md
  faq/how-do-i-hide-the-settings-button.html: faq/how-do-i-hide-the-settings-button.md
  faq/how-do-i-list-an-elements-connections-in-its-profile.html: faq/how-do-i-list-an-elements-connections-in-its-profile.md
  faq/how-do-i-make-sense-of-my-receipt.html: faq/how-do-i-make-sense-of-my-receipt.md
  faq/how-do-i-map-sub-systems.html: faq/how-do-i-map-sub-systems.md
  faq/how-do-i-remove-opposite.html: faq/how-do-i-remove-opposite.md
  faq/how-do-i-rename-map-view.html: faq/how-do-i-rename-map-view.md
  faq/how-do-i-restructure-my-adjacency-matrix.html: faq/how-do-i-restructure-my-adjacency-matrix.md
  faq/how-do-i-select-options-by-default-in-my-control.html: faq/how-do-i-select-options-by-default-in-my-control.md
  faq/how-do-i-show-the-settings-button.html: faq/how-do-i-show-the-settings-button.md
  faq/how-do-i-size-elements-by-number-of-connections.html: faq/how-do-i-size-elements-by-number-of-connections.md
  faq/how-do-i-transfer-a-project.html: faq/how-do-i-transfer-a-project.md
  faq/how-do-i-update-credit-card.html: faq/how-do-i-update-credit-card.md
  faq/how-do-keep-elements-from-moving.html: faq/how-do-keep-elements-from-moving.md
  faq/how-much-data-can-kumu-handle.html: faq/how-much-data-can-kumu-handle.md
  faq/how-to-change-length-of-connections.html: faq/how-to-change-length-of-connections.md
  faq/how-to-get-rid-of-duplicates.html: faq/how-to-get-rid-of-duplicates.md
  faq/my-PDF-wont-export.html: faq/my-PDF-wont-export.md
  faq/my-map-disappeared-how-do-i-bring-it-back.html: faq/my-map-disappeared-how-do-i-bring-it-back.md
  faq/what-are-loops.html: faq/what-are-loops.md
  faq/what-pricing-plans-does-Kumu-have.html: faq/what-pricing-plans-does-Kumu-have.md
  faq/where-can-i-find-invoices.html: faq/where-can-i-find-invoices.md
  getting-started/faq.html: getting-started/faq.md
  getting-started/first-steps.html: getting-started/first-steps.md
  getting-started/kumu-101.html: getting-started/kumu-101.md
  getting-started/quick-tips.html: getting-started/quick-tips.md
  getting-started/webinars.html: getting-started/webinars.md
  guides/activity-feed.html: guides/activity-feed.md
  guides/add-ons.html: guides/add-ons.md
  guides/add-ons/disqus.html: guides/add-ons/disqus.md
  guides/advanced-settings.html: guides/advanced-settings.md
  guides/archiving-projects.html: guides/archiving-projects.md
  guides/blueprints.html: guides/blueprints.md
  guides/bridge.html: guides/bridge.md
  guides/clustering.html: guides/clustering.md
  guides/color-reference.html: guides/color-reference.md
  guides/computed-fields.html: guides/computed-fields.md
  guides/controls.html: guides/controls.md
  guides/controls/cluster-control.html: guides/controls/cluster-control.md
  guides/controls/color-legend-control.html: guides/controls/color-legend-control.md
  guides/controls/controls-reference.html: guides/controls/controls-reference.md
  guides/controls/filter-control.html: guides/controls/filter-control.md
  guides/controls/image-control.html: guides/controls/image-control.md
  guides/controls/label-control.html: guides/controls/label-control.md
  guides/controls/showcase-by-field-control.html: guides/controls/showcase-by-field-control.md
  guides/controls/showcase-control.html: guides/controls/showcase-control.md
  guides/controls/sna-dashboard-control.html: guides/controls/sna-dashboard-control.md
  guides/controls/tagged-timeline-control.html: guides/controls/tagged-timeline-control.md
  guides/controls/text-control.html: guides/controls/text-control.md
  guides/controls/title-control.html: guides/controls/title-control.md
  guides/controls/view-toggle-control.html: guides/controls/view-toggle-control.md
  guides/data-driven-decorations.html: guides/data-driven-decorations.md
  guides/decorate.html: guides/decorate.md
  guides/default-view-settings.html: guides/default-view-settings.md
  guides/default-settings.html: guides/default-view-settings.md
  guides/direct-decorations.html: guides/direct-decorations.md
  guides/disciplines/README.html: guides/disciplines/README.md
  guides/embeds.html: guides/share-and-embed.md
  guides/export.html: guides/export.md
  guides/fields.html: guides/fields.md
  guides/filter.html: guides/filter.md
  guides/flags.html: guides/flags.md
  guides/focus.html: guides/focus.md
  guides/forking.html: guides/forking.md
  guides/guides.html: guides/guides.md
  guides/icons.html: guides/icons.md
  guides/images.html: guides/images.md
  guides/import.html: guides/import.md
  guides/imported-views.html: guides/imported-views.md
  guides/issues.html: guides/issues.md
  guides/label-templates.html: guides/label-templates.md
  guides/layouts.html: guides/layouts.md
  guides/layouts/fixed.html: guides/layouts/fixed.md
  guides/layouts/force-atlas.html: guides/layouts/force-atlas.md
  guides/layouts/force-directed.html: guides/layouts/force-directed.md
  guides/layouts/remove-overlap.html: guides/layouts/remove-overlap.md
  guides/layouts/scatter.html: guides/layouts/scatter.md
  guides/layouts/snap-to.html: guides/layouts/snap-to.md
  guides/legends.html: guides/legends.md
  guides/licensing.html: guides/licensing.md
  guides/lightbox.html: guides/lightbox.md
  guides/markdown.html: guides/markdown.md
  guides/metrics.html: guides/metrics.md
  guides/multi-factor-authentication.html: guides/multi-factor-authentication.md
  guides/partial-views.html: guides/partial-views.md
  guides/perspectives-advanced.html: overview/user-interfaces/view-editors.md#advanced-editor
  guides/popovers.html: guides/popovers.md
  guides/presentations.html: guides/presentations.md
  guides/pro-workspaces.html: guides/pro-workspaces.md
  guides/profiles.html: guides/profiles.md
  guides/project-admin.html: guides/project-admin.md
  guides/property-reference.html: guides/property-reference.md
  guides/quick-actions.html: guides/quick-actions.md
  guides/selector-reference.html: guides/selector-reference.md
  guides/selectors.html: guides/selectors.md
  guides/settings-reference.html: guides/settings-reference.md
  guides/shapes.html: guides/shapes.md
  guides/share-and-embed.html: guides/share-and-embed.md
  guides/shortcuts.html: guides/shortcuts.md
  guides/showcase.html: guides/showcase.md
  guides/single-sign-on.html: guides/single-sign-on.md
  guides/slugs.html: guides/slugs.md
  guides/sna-network-mapping.html: guides/sna-network-mapping.md
  guides/snap-to.html: /guides/layouts/snap-to.md
  guides/stakeholder-analysis.html: guides/stakeholder-analysis.md
  guides/system-mapping.html: guides/system-mapping.md
  guides/systems-practice.html: guides/systems-practice.md
  guides/table.html: guides/table.md
  guides/templates.html: guides/templates.md
  guides/templates/geo.html: guides/templates/geo.md
  guides/tracking.html: guides/tracking.md
  guides/underlays.html: guides/underlays.md
  guides/urls.html: guides/urls.md
  guides/views-advanced.html: guides/views-advanced.md
  guides/views.html: guides/views.md
  guides/widgets.html: guides/widgets.md
  other/changelabs.html: other/changelabs.md
  overview/accounts-and-plans.html: overview/accounts-and-plans.md
  overview/accounts-and-workspaces.html: overview/accounts-and-workspaces.md
  overview/actions-and-permissions.html: overview/actions-and-permissions.md
  overview/advanced-editor-hub.html: overview/advanced-editor-hub.md
  overview/billing.html: overview/billing.md
  overview/collaboration.html: overview/collaboration.md
  overview/dashboard.html: overview/dashboard.md
  overview/how-to-learn-kumu.html: overview/how-to-learn-kumu.md
  overview/kumu-io-and-kumu-enterprise.html: overview/kumu-io-and-kumu-enterprise.md
  overview/kumus-architecture.html: overview/kumus-architecture.md
  overview/map-editor.html: overview/map-editor.md
  overview/security.html: overview/security.md
  overview/settings.html: overview/settings.md
  overview/user-interfaces.html: overview/user-interfaces.md
  overview/view-editors.html: overview/view-editors.md
